TOKEN = "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"
GUARDRAIL_TOKEN = "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"
PATH_TO_RESPONSES = "responses"
CLASSIFIER_THRESHOLD = 0.7
PATH_TO_RESULTS = "results"
CURRENT_GUARDRAIL = "..."
CURRENT_LLM = "..."